main: ${groupId}.${artifactId}.${name}
name: ${name}
version: ${version}
description: ${description}
author: ${author}
#commands:
#  ${artifactId}:
#    description: The main command for ${name}
#    aliases: [alias1,alias2]
#    usage: "\u00A7cRayzr fracked something up."